version: '2'

services:
  server:
    image: mysql
    container_name: server
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - net
  
  client:
    image: mysql
    container_name: client
    ports:
      - 6603:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - net

networks:
  net:
    driver: bridge
